In [174]:
import torch
import csv
import os
from transformers import ElectraTokenizer, ElectraConfig, AutoModelForSequenceClassification
from torch.utils.data import TensorDataset, DataLoader
import logging
from fastprogress.fastprogress import master_bar, progress_bar
from transformers.modeling_electra import ElectraModel, ElectraPreTrainedModel
import glob
logger = logging.getLogger(__name__)
import tqdm
import numpy as np

In [2]:
model = torch.load("./model/koELECTRA_epoch7")

In [4]:
input_file = './data/nsmc/ko_data.txt'
result_file = './koELECTRA_data.csv'

In [9]:
def load_data(path):
    result = []
    with open(path, "r") as f:
        for line in f:
            result.append(line.strip())
    return result

In [10]:
expectations = ['Predicted']

print(load_data(input_file)[:3])

['정말 많이 울었던 영화입니다.', '시간 낭비예요.', '포스터를 저렇게밖에 만들지 못했던 제작자의 소심함에 침을 뱉고 싶다.']


In [31]:
args = {
  "task": "nsmc",
  "data_dir": "data",
  "ckpt_dir": "ckpt",
  "train_file": "ratings_train.txt",
  "dev_file": "",
  "test_file": "ko_data.txt",
  "evaluate_test_during_training": True,
  "eval_all_checkpoints": True,
  "save_optimizer": False,
  "do_lower_case": False,
  "do_train": True,
  "do_eval": True,
  "max_seq_len": 50,
  "num_train_epochs": 8,
  "weight_decay": 0.0,
  "gradient_accumulation_steps": 1,
  "adam_epsilon": 1e-8,
  "warmup_steps": 0,
  "max_steps": -1,
  "max_grad_norm": 1.0,
  "no_cuda": False,
  "model_type": "koelectra-base-v2",
  "model_name_or_path": "monologg/koelectra-base-v2-discriminator",
  "output_dir": "koelectra-base-v2-nsmc-ckpt",
  "seed": 42,
  "train_batch_size": 64,
  "eval_batch_size": 128,
  "logging_steps": 2000,
  "save_steps": 2000,
  "learning_rate": 5e-5
}

In [83]:
class NsmcProcessor(object):
    """Processor for the NSMC data set """

    def __init__(self, args):
        self.args = args

    def get_labels(self):
        return ["0", "1"]

    @classmethod
    def _read_file(cls, input_file):
        """Reads a tab separated value file."""
        with open(input_file, "r", encoding="utf-8") as f:
            lines = []
            for line in f:
                lines.append(line.strip())
            return lines

    def _create_examples(self, lines, set_type):
        """Creates examples for the training and dev sets."""
        examples = []
        for (i, line) in enumerate(lines):
            guid = "%s-%s" % (set_type, i)
            text_a = line
            if i % 10000 == 0:
                logger.info(line)
            examples.append(InputExample(guid=guid, text_a=text_a, text_b=None))
        return examples

    def get_examples(self, mode):
        """
        Args:
            mode: train, dev, test
        """
        file_to_read = None
        if mode == 'train':
            file_to_read = self.args.train_file
        elif mode == 'dev':
            file_to_read = self.args.dev_file
        elif mode == 'test':
            file_to_read = "ko_data.txt"
        logger.info("LOOKING AT {}".format(os.path.join("data", "nsmc", file_to_read)))
        return self._create_examples(self._read_file(os.path.join("data", "nsmc", file_to_read)), mode)

In [84]:
class InputExample(object):
    """
    A single training/test example for simple sequence classification.
    """

    def __init__(self, guid, text_a, text_b):
        self.guid = guid
        self.text_a = text_a
        self.text_b = text_b

    def __repr__(self):
        return str(self.to_json_string())

    def to_dict(self):
        """Serializes this instance to a Python dictionary."""
        output = copy.deepcopy(self.__dict__)
        return output

    def to_json_string(self):
        """Serializes this instance to a JSON string."""
        return json.dumps(self.to_dict(), indent=2, sort_keys=True) + "\n"

In [91]:
class InputFeatures(object):
    """A single set of features of data."""

    def __init__(self, input_ids, attention_mask, token_type_ids):
        self.input_ids = input_ids
        self.attention_mask = attention_mask
        self.token_type_ids = token_type_ids

    def __repr__(self):
        return str(self.to_json_string())

    def to_dict(self):
        """Serializes this instance to a Python dictionary."""
        output = copy.deepcopy(self.__dict__)
        return output

    def to_json_string(self):
        """Serializes this instance to a JSON string."""
        return json.dumps(self.to_dict(), indent=2, sort_keys=True) + "\n"

In [98]:
def seq_cls_load_and_cache_examples(args, tokenizer, mode):
    processor = NsmcProcessor(args)
    output_mode = "classification"
    # Load data features from cache or dataset file
    cached_features_file = os.path.join('./data', "cached_nsmc_koelectra-base-v2-discriminator_50_{}".format(mode))
    if os.path.exists(cached_features_file):
        logger.info("Loading features from cached file %s", cached_features_file)
        features = torch.load(cached_features_file)
    else:
        logger.info("Creating features from dataset file at %s", "./data")
        if mode == "train":
            examples = processor.get_examples("train")
        elif mode == "dev":
            examples = processor.get_examples("dev")
        elif mode == "test":
            examples = processor.get_examples("test")
        else:
            raise ValueError("For mode, only train, dev, test is avaiable")
        features = seq_cls_convert_examples_to_features(args, examples, tokenizer, 50, "nsmc")
        logger.info("Saving features into cached file %s", cached_features_file)
        torch.save(features, cached_features_file)

    # Convert to Tensors and build dataset
    all_input_ids = torch.tensor([f.input_ids for f in features], dtype=torch.long)
    all_attention_mask = torch.tensor([f.attention_mask for f in features], dtype=torch.long)
    all_token_type_ids = torch.tensor([f.token_type_ids for f in features], dtype=torch.long)
#     if output_mode == "classification":
#         all_labels = torch.tensor([f.label for f in features], dtype=torch.long)
#     elif output_mode == "regression":
#         all_labels = torch.tensor([f.label for f in features], dtype=torch.float)

    dataset = TensorDataset(all_input_ids, all_attention_mask, all_token_type_ids)
    return dataset

In [99]:
def seq_cls_convert_examples_to_features(
        args,
        examples,
        tokenizer,
        max_length,
        task
):
    processor = NsmcProcessor(args)
    label_list = processor.get_labels()
    logger.info("Using label list {} for task {}".format(label_list, "nsmc"))
    output_mode = "classification"
    logger.info("Using output mode {} for task {}".format(output_mode, "nsmc"))

    label_map = {label: i for i, label in enumerate(label_list)}

    def label_from_example(example):
        if output_mode == "classification":
            return label_map[example.label]
        elif output_mode == "regression":
            return float(example.label)
        raise KeyError(output_mode)

    batch_encoding = tokenizer.batch_encode_plus(
        [(example.text_a, example.text_b) for example in examples], max_length=max_length, pad_to_max_length=True
    )

    features = []
    for i in range(len(examples)):
        inputs = {k: batch_encoding[k][i] for k in batch_encoding}
        if "token_type_ids" not in inputs:
            inputs["token_type_ids"] = [0] * len(inputs["input_ids"])  # For xlm-roberta

        feature = InputFeatures(**inputs)
        features.append(feature)

    for i, example in enumerate(examples[:5]):
        logger.info("*** Example ***")
        logger.info("guid: {}".format(example.guid))
        logger.info("input_ids: {}".format(" ".join([str(x) for x in features[i].input_ids])))
        logger.info("attention_mask: {}".format(" ".join([str(x) for x in features[i].attention_mask])))
        logger.info("token_type_ids: {}".format(" ".join([str(x) for x in features[i].token_type_ids])))

    return features

In [100]:
tokenizer = ElectraTokenizer.from_pretrained("monologg/koelectra-base-v2-discriminator", do_lower_case=False)

In [101]:
data_set = seq_cls_load_and_cache_examples(args, tokenizer, mode="test")

In [116]:
dataloader = DataLoader(data_set, batch_size= 128)

In [152]:
len(dataloader)

88

In [125]:
class ElectraForSequenceClassification(ElectraPreTrainedModel):
    def __init__(self, config):
        super().__init__(config)
        self.num_labels = config.num_labels

        self.electra = ElectraModel(config)
        self.dropout = nn.Dropout(config.hidden_dropout_prob)
        self.classifier = nn.Linear(config.hidden_size, config.num_labels)

        self.init_weights()

    def forward(
            self,
            input_ids=None,
            attention_mask=None,
            token_type_ids=None,
            position_ids=None,
            head_mask=None,
            inputs_embeds=None,
            labels=None,
    ):
        discriminator_hidden_states = self.electra(
            input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds
        )
        pooled_output = discriminator_hidden_states[0][:, 0]

        pooled_output = self.dropout(pooled_output)
        logits = self.classifier(pooled_output)

        outputs = (logits,) + discriminator_hidden_states[1:]  # add hidden states and attention if they are here

        if labels is not None:
            if self.num_labels == 1:
                #  We are doing regression
                loss_fct = MSELoss()
                loss = loss_fct(logits.view(-1), labels.view(-1))
            else:
                loss_fct = CrossEntropyLoss()
                loss = loss_fct(logits.view(-1, self.num_labels), labels.view(-1))
            outputs = (loss,) + outputs

        return outputs  # (loss), logits, (hidden_states), (attentions)

In [145]:
checkpoints = list(
            os.path.dirname(c) for c in sorted(glob.glob("./ckpt/koelectra-base-v2-nsmc-ckpt" + "/**/" + "pytorch_model.bin", recursive=True)))

In [170]:
checkpoints

['./ckpt/koelectra-base-v2-nsmc-ckpt/checkpoint-10000',
 './ckpt/koelectra-base-v2-nsmc-ckpt/checkpoint-12000',
 './ckpt/koelectra-base-v2-nsmc-ckpt/checkpoint-14000',
 './ckpt/koelectra-base-v2-nsmc-ckpt/checkpoint-16000',
 './ckpt/koelectra-base-v2-nsmc-ckpt/checkpoint-18000',
 './ckpt/koelectra-base-v2-nsmc-ckpt/checkpoint-2000',
 './ckpt/koelectra-base-v2-nsmc-ckpt/checkpoint-20000',
 './ckpt/koelectra-base-v2-nsmc-ckpt/checkpoint-4000',
 './ckpt/koelectra-base-v2-nsmc-ckpt/checkpoint-6000',
 './ckpt/koelectra-base-v2-nsmc-ckpt/checkpoint-8000']

In [150]:
global_step = checkpoints[0].split("-")[-1]

In [195]:
model = ElectraForSequenceClassification.from_pretrained('./ckpt/koelectra-base-v2-nsmc-ckpt/checkpoint-2000')


NameError: name 'nn' is not defined

In [196]:
for batch in progress_bar(dataloader):
        model.eval()
        batch = tuple(t.to(args.device) for t in batch)

        with torch.no_grad():
            inputs = {
                "input_ids": batch[0],
                "attention_mask": batch[1],
                "labels": batch[3]
            }
            if args.model_type not in ["distilkobert", "xlm-roberta"]:
                inputs["token_type_ids"] = batch[2]  # Distilkobert, XLM-Roberta don't use segment_ids
            outputs = model(**inputs)
            tmp_eval_loss, logits = outputs[:2]

            eval_loss += tmp_eval_loss.mean().item()
        nb_eval_steps += 1
        if preds is None:
            preds = logits.detach().cpu().numpy()
            out_label_ids = inputs["labels"].detach().cpu().numpy()
        else:
            preds = np.append(preds, logits.detach().cpu().numpy(), axis=0)
            out_label_ids = np.append(out_label_ids, inputs["labels"].detach().cpu().numpy(), axis=0)

AttributeError: 'collections.OrderedDict' object has no attribute 'device'

In [197]:
args = torch.load(os.path.join("./model", 'koELECTRA_epoch7'))

In [198]:
args

OrderedDict([('electra.embeddings.word_embeddings.weight',
              tensor([[-0.0283,  0.0494, -0.0420,  ..., -0.0797,  0.0883, -0.0482],
                      [-0.0239, -0.0071,  0.1551,  ...,  0.0486, -0.1820, -0.0018],
                      [-0.0736,  0.0154, -0.0066,  ..., -0.1031,  1.0226,  0.0610],
                      ...,
                      [-0.0281,  0.0449, -0.0198,  ..., -0.0735,  0.0658, -0.0386],
                      [-0.0325,  0.0351, -0.0340,  ..., -0.0739,  0.0923, -0.0515],
                      [-0.0292,  0.0421, -0.0447,  ..., -0.0719,  0.0842, -0.0380]],
                     device='cuda:0')),
             ('electra.embeddings.position_embeddings.weight',
              tensor([[-5.7810e-02,  4.0580e-02,  3.1330e-03,  ..., -7.6071e-02,
                        1.2335e+00,  7.0402e-02],
                      [ 3.6186e-03,  7.6510e-03,  5.8032e-02,  ...,  2.4272e-02,
                       -1.1143e-01,  9.9718e-03],
                      [ 1.3220e-02, -3.6738e

In [200]:
model = AutoModelForSequenceClassification.from_pretrained('./ckpt/koelectra-base-v2-nsmc-ckpt/checkpoint-2000')  # Config will be automatically loaded from model_dir
model.to("cuda")
model.eval()
logger.info("***** Model Loaded *****")

In [201]:
model = load_model

NameError: name 'load_model' is not defined

In [202]:
result = []
for batch in dataloader:
    batch = tuple(t.to("cuda") for t in batch)
    with torch.no_grad():
        inputs = {"input_ids": batch[0],
              "attention_mask": batch[1],
              "labels": None}
        outputs = model(**inputs)
        logits = outputs[0]
        print(logits)
        result.append(logits)
print(len(result))

tensor([[ 8.1487e-02, -2.0092e-01],
        [-4.9352e-02, -1.2332e-01],
        [ 7.8471e-02, -2.3849e-01],
        [-3.9268e-02, -7.4065e-02],
        [ 2.5782e-02, -2.0974e-01],
        [ 4.3766e-03, -1.3649e-01],
        [-1.2409e-03, -1.5019e-01],
        [ 9.6684e-02, -2.1868e-01],
        [ 1.0886e-01, -2.4166e-01],
        [ 1.2199e-01, -2.2383e-01],
        [ 1.3190e-02, -1.2043e-01],
        [ 8.5075e-02, -2.5102e-01],
        [ 1.3123e-01, -2.3997e-01],
        [-1.1926e-04, -1.4805e-01],
        [ 7.7764e-02, -2.1178e-01],
        [ 5.9854e-02, -1.6608e-01],
        [ 7.8130e-02, -1.8938e-01],
        [ 1.2916e-01, -2.3374e-01],
        [ 1.0572e-01, -2.2612e-01],
        [ 4.4560e-02, -1.6021e-01],
        [ 3.7387e-02, -1.4721e-01],
        [ 1.8608e-02, -1.4677e-01],
        [ 2.0427e-02, -1.5380e-01],
        [ 1.1802e-01, -2.1344e-01],
        [ 5.1566e-03, -2.0435e-01],
        [ 7.1172e-02, -2.4105e-01],
        [ 1.1058e-01, -2.0622e-01],
        [ 1.2500e-01, -2.609

tensor([[ 0.0425, -0.2293],
        [ 0.1381, -0.2520],
        [-0.0288, -0.1040],
        [ 0.1026, -0.2650],
        [ 0.0841, -0.1881],
        [ 0.0612, -0.1692],
        [ 0.0239, -0.2202],
        [ 0.0969, -0.2407],
        [ 0.1115, -0.2267],
        [ 0.1332, -0.2145],
        [ 0.0611, -0.2133],
        [ 0.0983, -0.2879],
        [ 0.0908, -0.2000],
        [ 0.1210, -0.2235],
        [ 0.0994, -0.2132],
        [-0.0064, -0.1935],
        [ 0.1306, -0.2145],
        [ 0.0607, -0.1676],
        [ 0.0653, -0.1692],
        [ 0.0297, -0.1394],
        [ 0.1246, -0.2468],
        [ 0.1217, -0.2388],
        [ 0.0624, -0.2128],
        [ 0.0008, -0.1815],
        [-0.0287, -0.1632],
        [ 0.0964, -0.2047],
        [ 0.0190, -0.1981],
        [ 0.1122, -0.2096],
        [ 0.0667, -0.2668],
        [ 0.1308, -0.2420],
        [ 0.0161, -0.1937],
        [-0.0192, -0.1899],
        [ 0.0141, -0.1986],
        [ 0.0692, -0.2655],
        [ 0.0809, -0.2550],
        [ 0.1011, -0

tensor([[ 0.0425, -0.1549],
        [ 0.1009, -0.2632],
        [ 0.1356, -0.2377],
        [ 0.0606, -0.2304],
        [-0.0128, -0.1155],
        [ 0.0552, -0.1903],
        [ 0.0448, -0.1525],
        [ 0.0926, -0.2714],
        [ 0.1345, -0.2201],
        [ 0.0693, -0.2145],
        [ 0.0577, -0.2288],
        [ 0.0729, -0.2031],
        [ 0.1216, -0.2413],
        [-0.0375, -0.0984],
        [ 0.1246, -0.2333],
        [ 0.0574, -0.2139],
        [ 0.0142, -0.1458],
        [-0.0218, -0.1369],
        [ 0.0443, -0.1694],
        [-0.0087, -0.2378],
        [ 0.0678, -0.2270],
        [ 0.1415, -0.2499],
        [ 0.0882, -0.2077],
        [ 0.0569, -0.1847],
        [ 0.0325, -0.2108],
        [ 0.1450, -0.2411],
        [ 0.0016, -0.1267],
        [ 0.0025, -0.1341],
        [ 0.1205, -0.2597],
        [ 0.1195, -0.2418],
        [ 0.0513, -0.2479],
        [ 0.0714, -0.1749],
        [ 0.0171, -0.2102],
        [-0.0015, -0.1204],
        [ 0.1191, -0.2257],
        [ 0.0681, -0

tensor([[ 0.0570, -0.1677],
        [ 0.0893, -0.2333],
        [ 0.1062, -0.1956],
        [ 0.0071, -0.1972],
        [-0.0141, -0.1137],
        [-0.0310, -0.2307],
        [-0.0074, -0.1660],
        [ 0.0417, -0.1739],
        [ 0.1004, -0.2449],
        [ 0.0817, -0.2510],
        [ 0.0946, -0.2228],
        [ 0.1263, -0.2183],
        [ 0.1252, -0.2233],
        [ 0.1109, -0.2345],
        [ 0.0801, -0.2173],
        [ 0.1189, -0.2659],
        [ 0.1119, -0.2393],
        [ 0.0827, -0.1923],
        [ 0.0525, -0.2496],
        [ 0.1432, -0.2712],
        [ 0.1435, -0.2241],
        [ 0.1240, -0.2308],
        [ 0.0239, -0.1581],
        [ 0.0973, -0.1952],
        [ 0.1326, -0.2352],
        [ 0.1378, -0.2313],
        [ 0.1284, -0.2225],
        [ 0.1136, -0.2553],
        [ 0.1054, -0.2350],
        [ 0.1198, -0.1929],
        [ 0.0754, -0.1746],
        [ 0.0568, -0.2187],
        [ 0.0623, -0.1839],
        [ 0.0403, -0.1547],
        [ 0.1177, -0.2388],
        [ 0.0918, -0

tensor([[ 0.1141, -0.2210],
        [ 0.0346, -0.1787],
        [ 0.1096, -0.2362],
        [ 0.0752, -0.1761],
        [ 0.1296, -0.2245],
        [ 0.1184, -0.2466],
        [ 0.1035, -0.2592],
        [ 0.0189, -0.1812],
        [ 0.1098, -0.2695],
        [-0.0478, -0.1462],
        [ 0.1324, -0.2348],
        [ 0.1132, -0.2608],
        [ 0.1119, -0.2399],
        [ 0.0354, -0.2409],
        [-0.0046, -0.1989],
        [ 0.1219, -0.2140],
        [ 0.1422, -0.2219],
        [ 0.0101, -0.1647],
        [ 0.1161, -0.2062],
        [ 0.0796, -0.2101],
        [ 0.0918, -0.2369],
        [ 0.0684, -0.2291],
        [ 0.1162, -0.2308],
        [ 0.0962, -0.2161],
        [ 0.1195, -0.2422],
        [ 0.1203, -0.2295],
        [ 0.1220, -0.2150],
        [ 0.1129, -0.2161],
        [ 0.0359, -0.2157],
        [ 0.1098, -0.2171],
        [ 0.0461, -0.1526],
        [ 0.1348, -0.2323],
        [ 0.0279, -0.2520],
        [ 0.0078, -0.1646],
        [ 0.1183, -0.2255],
        [ 0.1300, -0

tensor([[ 0.1023, -0.2194],
        [ 0.1090, -0.2463],
        [ 0.0758, -0.1985],
        [ 0.0173, -0.2184],
        [ 0.0730, -0.2043],
        [ 0.1066, -0.2857],
        [ 0.0246, -0.1375],
        [ 0.1178, -0.2531],
        [ 0.1249, -0.2399],
        [ 0.0577, -0.1743],
        [ 0.1448, -0.2497],
        [ 0.0469, -0.2133],
        [-0.0546, -0.1059],
        [ 0.0969, -0.2343],
        [-0.0274, -0.1251],
        [-0.0565, -0.1580],
        [ 0.1093, -0.2295],
        [ 0.1188, -0.2550],
        [ 0.0514, -0.1932],
        [ 0.0800, -0.2615],
        [ 0.0586, -0.1682],
        [-0.0426, -0.0975],
        [-0.0318, -0.1236],
        [-0.0247, -0.1978],
        [ 0.0077, -0.1701],
        [ 0.0504, -0.1885],
        [ 0.0871, -0.2201],
        [ 0.0596, -0.1792],
        [ 0.0117, -0.2061],
        [ 0.1128, -0.2348],
        [ 0.0527, -0.2019],
        [ 0.0359, -0.1765],
        [ 0.0754, -0.1746],
        [ 0.0674, -0.1659],
        [ 0.0433, -0.1709],
        [ 0.1157, -0

tensor([[ 1.1329e-01, -2.5107e-01],
        [ 2.3559e-03, -1.2279e-01],
        [ 5.3201e-02, -2.1346e-01],
        [ 7.2063e-02, -1.8852e-01],
        [ 1.3843e-01, -2.8631e-01],
        [ 1.0505e-01, -2.5023e-01],
        [ 1.1184e-01, -2.3549e-01],
        [ 1.1079e-01, -2.5393e-01],
        [ 1.1220e-01, -1.8633e-01],
        [ 1.1643e-01, -2.1585e-01],
        [ 5.9411e-02, -1.5735e-01],
        [ 8.8800e-02, -2.3746e-01],
        [ 3.6283e-02, -1.5840e-01],
        [ 6.7726e-02, -1.9496e-01],
        [ 1.2977e-01, -2.3046e-01],
        [ 1.7311e-02, -2.3631e-01],
        [ 9.3532e-02, -1.8881e-01],
        [ 1.1245e-01, -2.0867e-01],
        [ 1.1763e-01, -2.4995e-01],
        [ 5.9051e-02, -1.7215e-01],
        [ 1.0127e-01, -2.0712e-01],
        [ 1.3059e-01, -2.3286e-01],
        [-2.8949e-02, -9.2265e-02],
        [ 1.0562e-01, -2.3409e-01],
        [-1.7824e-02, -1.8019e-01],
        [ 1.2303e-01, -2.1607e-01],
        [ 7.5575e-02, -1.9500e-01],
        [ 1.1956e-01, -2.187

tensor([[ 0.1010, -0.1715],
        [ 0.0405, -0.1869],
        [ 0.0742, -0.2274],
        [ 0.0947, -0.2277],
        [ 0.1235, -0.2381],
        [ 0.1360, -0.2542],
        [-0.0351, -0.0701],
        [ 0.1117, -0.2280],
        [ 0.0607, -0.1676],
        [ 0.1217, -0.2482],
        [ 0.1379, -0.2464],
        [ 0.1060, -0.2139],
        [ 0.1092, -0.2336],
        [ 0.1285, -0.2193],
        [ 0.1073, -0.2424],
        [ 0.1163, -0.2387],
        [ 0.0461, -0.2058],
        [-0.0087, -0.1053],
        [ 0.1366, -0.2254],
        [ 0.1124, -0.2386],
        [ 0.1234, -0.2331],
        [-0.0122, -0.1306],
        [-0.0170, -0.1711],
        [ 0.0658, -0.1648],
        [ 0.1213, -0.2313],
        [ 0.0940, -0.2275],
        [ 0.1012, -0.2188],
        [ 0.1225, -0.2005],
        [ 0.1400, -0.2376],
        [ 0.0773, -0.1832],
        [ 0.1062, -0.1956],
        [-0.0166, -0.2036],
        [ 0.0771, -0.2814],
        [-0.0235, -0.1151],
        [-0.0341, -0.1157],
        [ 0.1152, -0

tensor([[ 0.1192, -0.2336],
        [ 0.0425, -0.2207],
        [ 0.0223, -0.1643],
        [ 0.1205, -0.2289],
        [ 0.0479, -0.1755],
        [ 0.1291, -0.2365],
        [ 0.1307, -0.2357],
        [ 0.0773, -0.2150],
        [-0.0453, -0.0923],
        [ 0.1200, -0.2651],
        [ 0.1188, -0.2297],
        [ 0.1011, -0.1967],
        [ 0.1169, -0.2457],
        [ 0.1198, -0.2292],
        [ 0.1148, -0.2290],
        [-0.0030, -0.2512],
        [ 0.0961, -0.2364],
        [ 0.0590, -0.1756],
        [ 0.0385, -0.1526],
        [ 0.1245, -0.2265],
        [ 0.0373, -0.1563],
        [-0.0085, -0.2163],
        [-0.0376, -0.0963],
        [ 0.1213, -0.2395],
        [ 0.1380, -0.2521],
        [ 0.1093, -0.2081],
        [ 0.0615, -0.1760],
        [ 0.0467, -0.1904],
        [ 0.1156, -0.2580],
        [ 0.1025, -0.1910],
        [ 0.1221, -0.2511],
        [ 0.1024, -0.1956],
        [ 0.0312, -0.2418],
        [ 0.1003, -0.2180],
        [ 0.1254, -0.2231],
        [ 0.1003, -0

tensor([[-0.0067, -0.1943],
        [-0.0432, -0.0662],
        [ 0.1338, -0.2196],
        [ 0.1105, -0.2340],
        [-0.0417, -0.0978],
        [ 0.0769, -0.2188],
        [ 0.0674, -0.2066],
        [ 0.1191, -0.2269],
        [ 0.1030, -0.2186],
        [-0.0289, -0.1917],
        [ 0.1159, -0.2383],
        [ 0.1124, -0.2346],
        [ 0.1264, -0.2449],
        [ 0.0999, -0.2052],
        [ 0.0863, -0.2249],
        [ 0.1252, -0.1846],
        [ 0.1195, -0.2421],
        [ 0.0275, -0.1735],
        [ 0.0693, -0.1869],
        [ 0.1064, -0.2441],
        [-0.0466, -0.0967],
        [ 0.0501, -0.1809],
        [-0.0163, -0.1200],
        [ 0.0763, -0.1772],
        [ 0.1201, -0.2475],
        [-0.0158, -0.1240],
        [ 0.0691, -0.2096],
        [ 0.0697, -0.2344],
        [ 0.1255, -0.2368],
        [ 0.0529, -0.2349],
        [ 0.1027, -0.2185],
        [ 0.1180, -0.2769],
        [ 0.1312, -0.2549],
        [-0.0269, -0.2169],
        [ 0.1315, -0.2510],
        [ 0.1093, -0

tensor([[ 0.0985, -0.2752],
        [ 0.0364, -0.1895],
        [ 0.1063, -0.2421],
        [ 0.1097, -0.2162],
        [ 0.0381, -0.2476],
        [ 0.0288, -0.1608],
        [ 0.1245, -0.2393],
        [ 0.0845, -0.2671],
        [ 0.1034, -0.2215],
        [ 0.0083, -0.1686],
        [ 0.1272, -0.2340],
        [ 0.0943, -0.2512],
        [ 0.1308, -0.2464],
        [ 0.1061, -0.2521],
        [-0.0085, -0.1334],
        [ 0.1028, -0.2336],
        [ 0.0787, -0.2015],
        [ 0.0780, -0.2274],
        [ 0.0665, -0.2228],
        [ 0.0144, -0.1475],
        [ 0.0967, -0.2289],
        [ 0.0566, -0.1935],
        [ 0.1298, -0.2408],
        [ 0.0719, -0.2341],
        [ 0.0355, -0.2630],
        [ 0.1116, -0.2024],
        [ 0.1076, -0.2278],
        [-0.0032, -0.1861],
        [ 0.1131, -0.2464],
        [ 0.0395, -0.2433],
        [ 0.1296, -0.2337],
        [ 0.0031, -0.1262],
        [ 0.0802, -0.2120],
        [-0.0105, -0.2060],
        [ 0.1251, -0.2534],
        [ 0.0962, -0

tensor([[ 5.1213e-02, -1.6477e-01],
        [ 1.1485e-01, -2.5638e-01],
        [ 9.2212e-02, -2.0277e-01],
        [ 1.0210e-01, -2.1753e-01],
        [ 1.2893e-01, -2.1289e-01],
        [ 1.1159e-01, -2.1040e-01],
        [ 3.3010e-03, -1.3905e-01],
        [ 7.4473e-02, -2.1879e-01],
        [ 1.2079e-01, -2.1714e-01],
        [ 1.0456e-01, -2.3736e-01],
        [-1.2613e-04, -1.5160e-01],
        [ 1.1345e-01, -2.1824e-01],
        [ 6.3474e-02, -2.1733e-01],
        [ 2.8259e-04, -2.1292e-01],
        [ 6.4499e-02, -2.4942e-01],
        [ 1.0795e-01, -2.5859e-01],
        [ 1.3079e-01, -2.4962e-01],
        [ 5.1516e-03, -1.3521e-01],
        [ 9.3639e-02, -1.9739e-01],
        [-3.6330e-02, -1.4270e-01],
        [ 6.3360e-02, -1.4970e-01],
        [ 1.3005e-01, -2.3389e-01],
        [ 8.9864e-02, -2.2319e-01],
        [ 5.2753e-02, -1.9803e-01],
        [-9.9818e-03, -9.9597e-02],
        [-2.1388e-02, -1.8760e-01],
        [ 1.1756e-01, -2.5151e-01],
        [ 1.3144e-01, -2.582

tensor([[-0.0179, -0.1693],
        [ 0.0805, -0.2229],
        [ 0.1222, -0.2169],
        [ 0.1238, -0.2254],
        [-0.0509, -0.1538],
        [ 0.0997, -0.2060],
        [ 0.1125, -0.2526],
        [ 0.0627, -0.1950],
        [-0.0312, -0.0851],
        [ 0.1305, -0.2293],
        [ 0.0612, -0.1931],
        [-0.0208, -0.1930],
        [ 0.1096, -0.2397],
        [ 0.1003, -0.2224],
        [ 0.1030, -0.2550],
        [ 0.0533, -0.2392],
        [ 0.0411, -0.1757],
        [-0.0208, -0.1514],
        [ 0.0947, -0.1948],
        [ 0.0485, -0.1963],
        [ 0.1268, -0.2403],
        [ 0.0259, -0.2316],
        [-0.0205, -0.1244],
        [ 0.1057, -0.2235],
        [ 0.1071, -0.2399],
        [ 0.0953, -0.2541],
        [ 0.1158, -0.2572],
        [-0.0257, -0.1134],
        [ 0.0017, -0.1391],
        [ 0.0366, -0.1875],
        [ 0.1193, -0.2312],
        [ 0.1026, -0.2385],
        [ 0.0113, -0.1266],
        [-0.0056, -0.1484],
        [ 0.0034, -0.1331],
        [ 0.1214, -0

tensor([[ 0.0228, -0.2574],
        [ 0.0595, -0.1791],
        [ 0.0766, -0.1953],
        [ 0.1296, -0.2358],
        [ 0.0071, -0.1230],
        [ 0.0623, -0.1791],
        [ 0.1201, -0.2266],
        [ 0.1059, -0.2036],
        [ 0.0673, -0.2448],
        [ 0.1250, -0.2215],
        [ 0.1266, -0.2480],
        [ 0.1113, -0.2256],
        [ 0.0847, -0.2143],
        [ 0.0772, -0.2597],
        [ 0.1279, -0.2381],
        [-0.0005, -0.1447],
        [ 0.0399, -0.1571],
        [ 0.0944, -0.2848],
        [-0.0062, -0.1060],
        [ 0.0659, -0.1803],
        [ 0.1238, -0.2603],
        [ 0.0626, -0.2237],
        [ 0.0250, -0.1416],
        [-0.0069, -0.1160],
        [ 0.0927, -0.2117],
        [ 0.0849, -0.1842],
        [ 0.0612, -0.1539],
        [ 0.0859, -0.2029],
        [ 0.1053, -0.2398],
        [ 0.0817, -0.2294],
        [ 0.1083, -0.1966],
        [ 0.0662, -0.1970],
        [ 0.0508, -0.2059],
        [ 0.0014, -0.1597],
        [ 0.0602, -0.2388],
        [ 0.0954, -0

tensor([[ 0.1339, -0.2519],
        [ 0.0986, -0.2127],
        [ 0.0383, -0.2176],
        [ 0.0316, -0.1749],
        [ 0.0850, -0.2065],
        [ 0.1265, -0.2424],
        [ 0.1371, -0.2482],
        [ 0.1173, -0.2442],
        [ 0.0747, -0.2376],
        [ 0.1262, -0.2355],
        [ 0.0175, -0.2036],
        [-0.0179, -0.1738],
        [ 0.0287, -0.1388],
        [-0.0297, -0.2293],
        [ 0.1255, -0.2739],
        [ 0.0258, -0.1858],
        [ 0.0598, -0.1975],
        [ 0.0775, -0.2656],
        [ 0.1209, -0.2381],
        [ 0.0898, -0.2336],
        [-0.0241, -0.0992],
        [ 0.0099, -0.1109],
        [ 0.0900, -0.2247],
        [-0.0680, -0.1625],
        [ 0.1077, -0.2117],
        [ 0.1446, -0.2470],
        [ 0.1099, -0.2451],
        [-0.0166, -0.1862],
        [ 0.0777, -0.2667],
        [ 0.1245, -0.2293],
        [ 0.0630, -0.2187],
        [ 0.0466, -0.1905],
        [ 0.1098, -0.2409],
        [ 0.0242, -0.1650],
        [ 0.0714, -0.2513],
        [ 0.0990, -0

tensor([[ 0.0195, -0.1351],
        [ 0.1077, -0.2016],
        [ 0.1234, -0.2254],
        [ 0.1177, -0.2342],
        [ 0.0218, -0.1572],
        [ 0.0799, -0.2023],
        [-0.0067, -0.1364],
        [ 0.0534, -0.2502],
        [ 0.0041, -0.1302],
        [ 0.1028, -0.1968],
        [ 0.1198, -0.1929],
        [ 0.0881, -0.2182],
        [ 0.0328, -0.1739],
        [ 0.1329, -0.2280],
        [ 0.1039, -0.2537],
        [ 0.0832, -0.2136],
        [-0.0407, -0.1357],
        [ 0.1038, -0.2766],
        [ 0.0776, -0.2154],
        [ 0.0827, -0.1923],
        [-0.0034, -0.1434],
        [-0.0033, -0.1178],
        [ 0.0136, -0.1514],
        [ 0.1133, -0.1988],
        [ 0.1183, -0.2725],
        [ 0.0031, -0.1891],
        [ 0.1223, -0.2516],
        [ 0.0652, -0.2273],
        [ 0.1321, -0.2322],
        [ 0.0802, -0.2405],
        [ 0.0058, -0.1899],
        [ 0.1073, -0.2296],
        [ 0.0361, -0.2119],
        [ 0.0551, -0.2303],
        [ 0.1239, -0.2323],
        [ 0.0622, -0

tensor([[ 2.8651e-02, -2.2095e-01],
        [ 1.0132e-01, -2.4766e-01],
        [ 1.6653e-02, -1.4238e-01],
        [ 1.0080e-01, -2.5147e-01],
        [ 8.2035e-02, -2.3143e-01],
        [ 1.3477e-01, -2.6440e-01],
        [ 1.0784e-01, -2.4504e-01],
        [-2.6546e-02, -9.2227e-02],
        [-3.2270e-02, -1.5537e-01],
        [ 5.3499e-02, -2.2987e-01],
        [ 8.7643e-02, -2.0061e-01],
        [ 1.2561e-01, -2.2936e-01],
        [ 5.8756e-02, -2.3344e-01],
        [ 1.0850e-02, -1.6604e-01],
        [-8.9331e-03, -1.9386e-01],
        [-7.3742e-03, -1.1759e-01],
        [-1.8820e-02, -1.2915e-01],
        [ 1.1408e-01, -2.3080e-01],
        [ 7.9686e-02, -1.9261e-01],
        [ 2.1900e-02, -1.5831e-01],
        [ 8.7157e-02, -2.2973e-01],
        [-4.3781e-02, -1.4764e-01],
        [ 7.9096e-02, -2.3232e-01],
        [ 7.8698e-02, -2.5008e-01],
        [ 1.2518e-01, -2.3447e-01],
        [ 1.1762e-01, -2.4456e-01],
        [ 1.1239e-01, -2.5319e-01],
        [ 1.1191e-01, -2.345

tensor([[ 0.1293, -0.2301],
        [-0.0085, -0.1235],
        [ 0.0331, -0.1644],
        [ 0.1198, -0.1929],
        [ 0.1205, -0.2318],
        [ 0.0445, -0.2322],
        [ 0.0095, -0.2236],
        [ 0.0841, -0.1670],
        [ 0.1157, -0.2330],
        [ 0.1116, -0.2221],
        [ 0.1276, -0.2491],
        [ 0.0981, -0.2339],
        [ 0.0760, -0.1984],
        [-0.0471, -0.1463],
        [ 0.0910, -0.2320],
        [ 0.1227, -0.2285],
        [-0.0294, -0.1318],
        [ 0.0765, -0.2555],
        [ 0.1313, -0.2175],
        [ 0.1212, -0.2479],
        [ 0.0884, -0.2237],
        [ 0.1290, -0.2325],
        [-0.0251, -0.1742],
        [ 0.0550, -0.2228],
        [-0.0104, -0.1433],
        [ 0.0999, -0.2180],
        [ 0.0801, -0.1982],
        [-0.0024, -0.1881],
        [ 0.1198, -0.2246],
        [ 0.0594, -0.2227],
        [ 0.0229, -0.2140],
        [ 0.0295, -0.1495],
        [-0.0009, -0.2164],
        [ 0.1007, -0.2341],
        [ 0.0519, -0.1739],
        [ 0.0994, -0

tensor([[ 1.3088e-01, -2.1600e-01],
        [ 7.9025e-02, -2.6523e-01],
        [ 4.3415e-02, -1.7164e-01],
        [ 3.0633e-02, -1.6348e-01],
        [ 1.8104e-02, -1.8658e-01],
        [ 1.0389e-01, -2.0622e-01],
        [ 1.0403e-01, -2.3888e-01],
        [ 5.3410e-04, -1.0989e-01],
        [ 9.4563e-02, -1.9107e-01],
        [ 1.1701e-01, -2.0995e-01],
        [ 1.2555e-01, -2.4920e-01],
        [ 8.9948e-02, -1.8448e-01],
        [ 2.1750e-02, -1.5014e-01],
        [-9.9936e-03, -1.2694e-01],
        [-1.2210e-02, -1.4356e-01],
        [ 1.0950e-04, -2.1911e-01],
        [-3.5607e-02, -1.2473e-01],
        [ 1.1543e-01, -2.2758e-01],
        [ 7.8667e-03, -2.0065e-01],
        [ 2.0164e-03, -1.7236e-01],
        [ 8.2859e-02, -2.1808e-01],
        [ 3.2708e-02, -1.6751e-01],
        [ 5.3928e-02, -2.1040e-01],
        [ 5.7569e-02, -1.6773e-01],
        [-1.0119e-03, -1.9395e-01],
        [ 7.8864e-02, -2.3791e-01],
        [-1.0147e-03, -1.2820e-01],
        [ 1.3307e-01, -2.350

tensor([[ 3.9501e-02, -1.5230e-01],
        [ 5.2964e-02, -2.1775e-01],
        [ 1.1812e-01, -2.4655e-01],
        [ 1.3631e-01, -2.4119e-01],
        [ 3.0337e-02, -2.1421e-01],
        [ 1.7913e-02, -2.1583e-01],
        [ 1.2735e-01, -2.4193e-01],
        [ 6.0000e-02, -1.7707e-01],
        [-7.7263e-03, -1.1785e-01],
        [ 1.9364e-02, -1.3297e-01],
        [ 1.1976e-01, -1.9294e-01],
        [-2.9408e-02, -1.3183e-01],
        [ 1.2381e-01, -2.4907e-01],
        [ 4.9231e-02, -1.5445e-01],
        [ 3.2818e-02, -1.4130e-01],
        [-2.0836e-02, -1.7673e-01],
        [ 7.5089e-02, -2.1612e-01],
        [ 3.4733e-02, -1.9234e-01],
        [ 9.1198e-02, -2.5788e-01],
        [ 9.0875e-02, -1.8156e-01],
        [ 8.9822e-02, -2.5515e-01],
        [ 9.8665e-02, -2.5698e-01],
        [ 8.0127e-02, -2.5891e-01],
        [ 6.5302e-02, -2.1986e-01],
        [ 1.1074e-01, -2.3755e-01],
        [ 1.0223e-04, -1.3581e-01],
        [-5.5117e-02, -6.2377e-02],
        [ 1.1976e-01, -1.929

tensor([[ 1.2196e-02, -2.2093e-01],
        [ 8.6183e-02, -2.1717e-01],
        [ 7.0974e-03, -1.9535e-01],
        [ 7.8702e-02, -1.9862e-01],
        [ 1.1244e-01, -2.5538e-01],
        [ 7.0605e-02, -1.7624e-01],
        [ 5.8952e-03, -1.3313e-01],
        [ 1.3433e-02, -2.5620e-01],
        [ 1.2346e-01, -2.5808e-01],
        [ 6.4224e-02, -1.7650e-01],
        [-2.8561e-04, -1.3170e-01],
        [ 6.0548e-02, -1.9664e-01],
        [ 5.9473e-02, -2.4733e-01],
        [ 9.1808e-02, -1.9846e-01],
        [ 1.0360e-01, -2.0198e-01],
        [-2.0452e-02, -1.4687e-01],
        [ 2.4221e-02, -1.3971e-01],
        [ 8.7193e-02, -2.6808e-01],
        [ 1.2646e-01, -2.4882e-01],
        [-2.1343e-02, -1.8461e-01],
        [ 4.4715e-02, -2.0863e-01],
        [ 1.0617e-01, -1.9564e-01],
        [ 9.2757e-02, -2.4190e-01],
        [ 1.2058e-01, -2.3696e-01],
        [ 7.5167e-02, -1.7612e-01],
        [ 7.1606e-03, -1.7544e-01],
        [ 1.1984e-01, -2.5954e-01],
        [ 1.2845e-01, -2.406

tensor([[ 9.7029e-02, -2.2561e-01],
        [ 1.0415e-01, -2.5109e-01],
        [ 1.1585e-01, -2.3020e-01],
        [ 1.0430e-01, -2.4537e-01],
        [ 1.5548e-02, -2.4593e-01],
        [ 2.3559e-03, -1.2279e-01],
        [-2.8447e-02, -1.5431e-01],
        [ 1.0245e-01, -2.6274e-01],
        [ 6.6358e-02, -1.6584e-01],
        [ 1.0863e-01, -2.1372e-01],
        [-4.0776e-03, -1.6238e-01],
        [ 1.0002e-01, -2.2920e-01],
        [ 6.7604e-02, -1.7294e-01],
        [ 8.2326e-02, -2.1893e-01],
        [ 9.8262e-02, -1.8705e-01],
        [ 1.1151e-01, -1.8267e-01],
        [-4.8017e-02, -6.9881e-02],
        [ 1.2811e-01, -2.1383e-01],
        [ 1.0869e-01, -1.9309e-01],
        [ 7.3917e-02, -1.8916e-01],
        [ 1.3868e-01, -2.5150e-01],
        [ 1.2420e-01, -2.6961e-01],
        [ 1.0635e-02, -1.4219e-01],
        [-4.1186e-02, -1.5114e-01],
        [-4.8042e-02, -1.3182e-01],
        [-4.2228e-02, -1.0861e-01],
        [ 1.0796e-01, -2.5837e-01],
        [ 1.1338e-01, -2.684

tensor([[ 0.0652, -0.2434],
        [ 0.1098, -0.2479],
        [ 0.0281, -0.1677],
        [ 0.0337, -0.1365],
        [ 0.1207, -0.2442],
        [ 0.0010, -0.1464],
        [ 0.0969, -0.2449],
        [ 0.1063, -0.2538],
        [-0.0480, -0.1012],
        [ 0.0695, -0.2333],
        [ 0.1259, -0.2363],
        [ 0.0091, -0.1641],
        [ 0.0456, -0.2592],
        [ 0.0471, -0.2019],
        [-0.0020, -0.1563],
        [-0.0056, -0.1630],
        [ 0.1276, -0.2373],
        [ 0.0019, -0.1376],
        [-0.0100, -0.1769],
        [ 0.0922, -0.2552],
        [ 0.1160, -0.2726],
        [-0.0312, -0.1471],
        [ 0.1228, -0.2415],
        [ 0.1015, -0.2630],
        [ 0.0767, -0.2278],
        [ 0.0471, -0.1755],
        [ 0.0658, -0.2540],
        [-0.0021, -0.1843],
        [ 0.0132, -0.2352],
        [ 0.1276, -0.2144],
        [ 0.0927, -0.2595],
        [-0.0120, -0.1127],
        [ 0.0971, -0.1998],
        [-0.0033, -0.1937],
        [ 0.0622, -0.2021],
        [ 0.0512, -0

tensor([[ 8.3910e-02, -1.8318e-01],
        [-2.2736e-02, -1.5432e-01],
        [ 1.0626e-01, -2.1961e-01],
        [ 1.3014e-01, -2.5085e-01],
        [ 1.2051e-01, -2.5889e-01],
        [ 6.7846e-02, -2.3934e-01],
        [ 4.4631e-02, -1.7815e-01],
        [ 1.1795e-01, -2.3759e-01],
        [ 1.0507e-01, -2.3831e-01],
        [ 1.0008e-02, -1.3722e-01],
        [ 1.3372e-01, -2.4279e-01],
        [ 1.1093e-01, -2.4143e-01],
        [-4.4764e-02, -1.1035e-01],
        [ 5.6205e-02, -2.0190e-01],
        [ 8.8142e-02, -2.3691e-01],
        [ 1.2672e-01, -2.3555e-01],
        [-1.1199e-03, -1.1141e-01],
        [ 9.6559e-02, -2.2384e-01],
        [ 4.8268e-02, -1.6785e-01],
        [ 1.3177e-01, -2.1596e-01],
        [ 1.1377e-01, -2.1566e-01],
        [ 1.3716e-02, -1.3492e-01],
        [ 4.6792e-02, -2.2152e-01],
        [ 1.1482e-01, -2.6307e-01],
        [ 1.0215e-01, -2.3759e-01],
        [ 4.9274e-02, -1.7799e-01],
        [ 4.2985e-02, -1.4179e-01],
        [ 9.6448e-02, -2.114

tensor([[ 0.0987, -0.2261],
        [ 0.1103, -0.2549],
        [-0.0020, -0.1912],
        [ 0.1159, -0.2268],
        [ 0.1234, -0.2146],
        [-0.0194, -0.1583],
        [ 0.1092, -0.2090],
        [ 0.1372, -0.2673],
        [ 0.1184, -0.2380],
        [ 0.0996, -0.2260],
        [ 0.0324, -0.1992],
        [ 0.0404, -0.1760],
        [ 0.0434, -0.2179],
        [ 0.0044, -0.1811],
        [ 0.0422, -0.2171],
        [ 0.0475, -0.1877],
        [ 0.1118, -0.2244],
        [-0.0401, -0.1379],
        [ 0.0697, -0.2489],
        [ 0.0244, -0.1686],
        [-0.0352, -0.1463],
        [ 0.1168, -0.2679],
        [ 0.0945, -0.2153],
        [ 0.0552, -0.1728],
        [ 0.1293, -0.2489],
        [-0.0043, -0.2123],
        [ 0.1129, -0.2346],
        [ 0.1031, -0.2215],
        [ 0.0874, -0.2152],
        [ 0.1169, -0.2536],
        [ 0.1051, -0.2229],
        [ 0.0736, -0.2296],
        [ 0.0872, -0.2218],
        [ 0.0044, -0.1261],
        [ 0.0932, -0.2275],
        [ 0.1005, -0

tensor([[ 0.1459, -0.2410],
        [ 0.1122, -0.2336],
        [ 0.1186, -0.2723],
        [ 0.1242, -0.2425],
        [ 0.1194, -0.2398],
        [ 0.0696, -0.1728],
        [ 0.0372, -0.1668],
        [ 0.1165, -0.2372],
        [ 0.1033, -0.2212],
        [ 0.0410, -0.1819],
        [ 0.1306, -0.2581],
        [ 0.0370, -0.1729],
        [ 0.0770, -0.1901],
        [ 0.0144, -0.1939],
        [-0.0029, -0.1949],
        [ 0.1184, -0.2146],
        [ 0.0419, -0.2223],
        [ 0.0981, -0.2253],
        [ 0.1027, -0.2216],
        [-0.0414, -0.2004],
        [ 0.1008, -0.2362],
        [ 0.0670, -0.2251],
        [ 0.1276, -0.2921],
        [ 0.0947, -0.2586],
        [ 0.0954, -0.2795],
        [ 0.0537, -0.2175],
        [ 0.1191, -0.2308],
        [ 0.0239, -0.2126],
        [ 0.0120, -0.1690],
        [ 0.0529, -0.2397],
        [ 0.1226, -0.2324],
        [ 0.1455, -0.2111],
        [ 0.0107, -0.2015],
        [ 0.1144, -0.2355],
        [-0.0074, -0.1719],
        [ 0.1122, -0

tensor([[-0.0412, -0.0888],
        [-0.0322, -0.1480],
        [-0.0126, -0.2095],
        [-0.0012, -0.1471],
        [ 0.0257, -0.1228],
        [ 0.0976, -0.3105],
        [ 0.1147, -0.2399],
        [ 0.0952, -0.2246],
        [ 0.1035, -0.2601],
        [ 0.0251, -0.1846],
        [ 0.0884, -0.1957],
        [ 0.0957, -0.2308],
        [-0.0309, -0.1004],
        [ 0.0812, -0.2318],
        [ 0.1285, -0.2406],
        [ 0.0854, -0.2645],
        [ 0.0868, -0.1847],
        [ 0.1275, -0.2388],
        [ 0.0957, -0.2483],
        [ 0.0621, -0.1876],
        [ 0.0629, -0.1763],
        [-0.0092, -0.1456],
        [ 0.1318, -0.2422],
        [ 0.0436, -0.2750],
        [ 0.1156, -0.2155],
        [-0.0018, -0.1400],
        [ 0.0466, -0.1873],
        [ 0.1143, -0.2428],
        [ 0.0164, -0.1700],
        [ 0.1040, -0.2463],
        [ 0.0224, -0.1439],
        [ 0.0649, -0.1991],
        [ 0.0997, -0.2067],
        [ 0.0712, -0.2063],
        [ 0.1059, -0.2131],
        [ 0.0815, -0

tensor([[ 1.0380e-02, -1.8349e-01],
        [ 5.6136e-02, -2.2136e-01],
        [ 1.2479e-01, -2.4991e-01],
        [ 1.1972e-01, -2.0839e-01],
        [ 9.9011e-02, -2.5208e-01],
        [ 1.0285e-01, -2.4108e-01],
        [ 1.1449e-01, -2.2506e-01],
        [ 8.5923e-02, -2.1878e-01],
        [ 8.7489e-02, -1.9903e-01],
        [ 1.8552e-02, -1.4551e-01],
        [ 1.0528e-01, -1.9341e-01],
        [-1.1520e-02, -1.3111e-01],
        [ 1.2394e-01, -2.1662e-01],
        [ 9.8536e-02, -2.2662e-01],
        [ 1.1355e-01, -2.3568e-01],
        [-1.4030e-02, -1.6524e-01],
        [ 1.0920e-01, -2.2701e-01],
        [ 9.4800e-02, -2.2464e-01],
        [ 7.0604e-02, -1.8248e-01],
        [ 1.4442e-01, -2.7991e-01],
        [ 1.2194e-01, -2.3469e-01],
        [ 2.2283e-02, -1.3711e-01],
        [ 9.4276e-02, -2.2655e-01],
        [ 1.1227e-01, -2.4601e-01],
        [ 3.1110e-03, -2.0003e-01],
        [ 1.2132e-01, -2.4014e-01],
        [ 1.1823e-01, -2.2517e-01],
        [-3.6925e-02, -1.204

tensor([[ 0.0513, -0.2301],
        [ 0.1132, -0.2413],
        [ 0.1164, -0.2251],
        [-0.0221, -0.1701],
        [ 0.1147, -0.2492],
        [ 0.0983, -0.2647],
        [ 0.0250, -0.1601],
        [ 0.0681, -0.2510],
        [-0.0292, -0.1062],
        [ 0.0369, -0.1514],
        [ 0.0794, -0.1806],
        [ 0.1119, -0.2749],
        [ 0.1165, -0.2324],
        [ 0.0728, -0.2643],
        [ 0.1206, -0.2431],
        [ 0.0897, -0.2404],
        [ 0.1232, -0.2500],
        [ 0.0986, -0.1708],
        [ 0.1060, -0.2144],
        [ 0.0738, -0.2750],
        [ 0.1304, -0.2268],
        [ 0.1183, -0.2420],
        [ 0.0998, -0.2232],
        [ 0.0995, -0.1841],
        [ 0.0421, -0.2218],
        [ 0.1281, -0.2363],
        [ 0.1403, -0.2310],
        [ 0.0987, -0.2219],
        [ 0.0505, -0.1925],
        [ 0.1239, -0.2434],
        [ 0.1323, -0.2691],
        [ 0.1040, -0.2650],
        [ 0.0715, -0.2509],
        [ 0.0100, -0.1371],
        [ 0.1100, -0.2319],
        [ 0.0475, -0

tensor([[ 0.1202, -0.2332],
        [ 0.1323, -0.2291],
        [ 0.0835, -0.1868],
        [ 0.1320, -0.2287],
        [ 0.1269, -0.2361],
        [ 0.0653, -0.1876],
        [ 0.0523, -0.1983],
        [ 0.0883, -0.2567],
        [ 0.1139, -0.2287],
        [ 0.1289, -0.2446],
        [ 0.0889, -0.2282],
        [ 0.0092, -0.1253],
        [ 0.0098, -0.1388],
        [ 0.1267, -0.2320],
        [ 0.0822, -0.1915],
        [ 0.1016, -0.2009],
        [ 0.1085, -0.2258],
        [ 0.0607, -0.2334],
        [ 0.1015, -0.2526],
        [ 0.1183, -0.2077],
        [ 0.0972, -0.2069],
        [ 0.1234, -0.2559],
        [ 0.0512, -0.1615],
        [ 0.0409, -0.2006],
        [ 0.0634, -0.2023],
        [ 0.0332, -0.1664],
        [ 0.1199, -0.2280],
        [ 0.1181, -0.2272],
        [-0.0014, -0.1468],
        [ 0.0246, -0.1246],
        [ 0.1305, -0.2452],
        [ 0.0502, -0.1873],
        [ 0.0173, -0.1907],
        [ 0.1045, -0.1976],
        [ 0.0382, -0.1640],
        [ 0.0427, -0

tensor([[-0.0448, -0.1025],
        [ 0.0930, -0.2271],
        [-0.0055, -0.1100],
        [ 0.1287, -0.2408],
        [ 0.0240, -0.1465],
        [ 0.0977, -0.2332],
        [ 0.0479, -0.1966],
        [ 0.1311, -0.2256],
        [ 0.0540, -0.1924],
        [ 0.1155, -0.2210],
        [ 0.0467, -0.1861],
        [-0.0259, -0.1597],
        [ 0.1204, -0.2515],
        [ 0.0792, -0.2265],
        [-0.0179, -0.1060],
        [ 0.1174, -0.2209],
        [-0.0461, -0.0955],
        [ 0.0747, -0.2326],
        [ 0.0824, -0.2064],
        [ 0.1302, -0.2442],
        [ 0.0104, -0.1777],
        [-0.0734, -0.1137],
        [ 0.1110, -0.2547],
        [ 0.0470, -0.2085],
        [ 0.0872, -0.2239],
        [ 0.0228, -0.1418],
        [-0.0129, -0.1031],
        [ 0.0859, -0.2124],
        [ 0.0859, -0.2124],
        [ 0.1081, -0.2762],
        [ 0.1216, -0.2481],
        [ 0.0317, -0.1514],
        [ 0.0735, -0.1699],
        [ 0.1222, -0.2408],
        [ 0.1323, -0.2474],
        [ 0.0908, -0

tensor([[ 0.0496, -0.1572],
        [ 0.0775, -0.2240],
        [ 0.0037, -0.2282],
        [-0.0445, -0.1968],
        [ 0.0551, -0.2244],
        [-0.0287, -0.0803],
        [ 0.0298, -0.1885],
        [ 0.0565, -0.1940],
        [ 0.1144, -0.2170],
        [ 0.1159, -0.2182],
        [ 0.1170, -0.2570],
        [ 0.1207, -0.2327],
        [ 0.0549, -0.2009],
        [ 0.1232, -0.2642],
        [ 0.0014, -0.1769],
        [ 0.0576, -0.1645],
        [ 0.0552, -0.1812],
        [ 0.1193, -0.2404],
        [ 0.1215, -0.2409],
        [ 0.0658, -0.2086],
        [ 0.1291, -0.2396],
        [ 0.0597, -0.1879],
        [ 0.1256, -0.2217],
        [-0.0219, -0.1400],
        [ 0.1154, -0.2387],
        [ 0.0274, -0.2231],
        [ 0.0665, -0.2275],
        [ 0.0912, -0.2287],
        [ 0.0164, -0.2238],
        [ 0.0255, -0.1580],
        [-0.0065, -0.1243],
        [-0.0083, -0.1696],
        [ 0.1090, -0.2503],
        [ 0.0504, -0.1802],
        [ 0.1101, -0.2303],
        [ 0.0928, -0

tensor([[ 5.3045e-02, -2.0587e-01],
        [-2.6423e-02, -1.6655e-01],
        [ 9.0701e-02, -2.3596e-01],
        [ 4.5777e-02, -1.6679e-01],
        [ 1.9703e-02, -1.9700e-01],
        [-7.6273e-02, -3.9798e-02],
        [-4.6343e-04, -1.6790e-01],
        [ 3.5343e-02, -1.5251e-01],
        [ 1.2349e-01, -2.4625e-01],
        [ 5.4452e-02, -2.0674e-01],
        [ 6.3008e-02, -1.8689e-01],
        [ 1.0039e-01, -2.5365e-01],
        [ 1.0116e-01, -2.4849e-01],
        [ 1.8355e-02, -1.7955e-01],
        [ 9.7360e-02, -2.0921e-01],
        [-2.6336e-02, -1.8279e-01],
        [ 3.1878e-02, -1.7134e-01],
        [ 8.5459e-02, -1.9761e-01],
        [ 1.1013e-01, -2.2981e-01],
        [ 1.1939e-01, -2.8570e-01],
        [ 1.0559e-01, -2.4155e-01],
        [ 1.2570e-01, -2.3450e-01],
        [ 6.3606e-02, -2.1875e-01],
        [-2.7821e-02, -1.2151e-01],
        [-5.1208e-02, -1.1845e-01],
        [ 1.1892e-01, -2.2493e-01],
        [ 9.8933e-02, -1.9748e-01],
        [ 1.4068e-01, -2.272

tensor([[ 0.1005, -0.2337],
        [ 0.1000, -0.2454],
        [ 0.1024, -0.2584],
        [ 0.1001, -0.2378],
        [ 0.0966, -0.2496],
        [ 0.1152, -0.2206],
        [ 0.0386, -0.1909],
        [ 0.0078, -0.1924],
        [ 0.0538, -0.2309],
        [ 0.0643, -0.2388],
        [ 0.0722, -0.1841],
        [-0.0461, -0.1564],
        [ 0.1198, -0.2477],
        [-0.0160, -0.2166],
        [ 0.1385, -0.2433],
        [ 0.1387, -0.2173],
        [-0.0315, -0.1639],
        [ 0.0249, -0.1887],
        [ 0.0352, -0.1769],
        [ 0.1124, -0.2462],
        [ 0.0253, -0.1457],
        [ 0.0406, -0.1796],
        [ 0.1083, -0.2213],
        [ 0.1087, -0.2200],
        [ 0.0732, -0.2290],
        [ 0.0325, -0.1696],
        [ 0.1121, -0.2000],
        [ 0.1203, -0.2324],
        [-0.0418, -0.1208],
        [ 0.0381, -0.1717],
        [ 0.0373, -0.2030],
        [ 0.0673, -0.2476],
        [ 0.1235, -0.2056],
        [-0.0375, -0.1744],
        [ 0.1075, -0.2548],
        [ 0.1137, -0

tensor([[ 0.0036, -0.1712],
        [ 0.0236, -0.1621],
        [ 0.1433, -0.2263],
        [ 0.0336, -0.1477],
        [-0.0609, -0.1546],
        [ 0.0876, -0.2469],
        [ 0.1115, -0.2200],
        [ 0.0570, -0.2191],
        [ 0.1200, -0.2408],
        [-0.0402, -0.2063],
        [ 0.0529, -0.1758],
        [ 0.1084, -0.2338],
        [ 0.1317, -0.2493],
        [-0.0080, -0.1933],
        [-0.0274, -0.1744],
        [ 0.0851, -0.2395],
        [ 0.1136, -0.2267],
        [ 0.0387, -0.1701],
        [ 0.0107, -0.1151],
        [ 0.0547, -0.1694],
        [ 0.0644, -0.2056],
        [ 0.1335, -0.2734],
        [ 0.0157, -0.2022],
        [ 0.0118, -0.2001],
        [ 0.1146, -0.2243],
        [ 0.0887, -0.2280],
        [ 0.0170, -0.1361],
        [-0.0112, -0.1575],
        [ 0.0183, -0.1327],
        [ 0.1210, -0.2545],
        [ 0.1145, -0.2326],
        [-0.0142, -0.2491],
        [ 0.0743, -0.2064],
        [ 0.0856, -0.2443],
        [ 0.1252, -0.2284],
        [ 0.1267, -0

tensor([[ 0.1032, -0.2672],
        [ 0.1207, -0.2396],
        [ 0.1149, -0.2543],
        [ 0.1213, -0.2758],
        [ 0.0271, -0.1882],
        [ 0.0793, -0.2517],
        [ 0.0781, -0.2351],
        [ 0.0116, -0.1296],
        [ 0.0251, -0.1332],
        [ 0.0625, -0.1949],
        [ 0.0723, -0.1853],
        [ 0.1295, -0.2588],
        [-0.0042, -0.1142],
        [ 0.1228, -0.2510],
        [ 0.1316, -0.2432],
        [ 0.0829, -0.2499],
        [-0.0506, -0.2054],
        [-0.0254, -0.1298],
        [-0.0355, -0.1556],
        [ 0.0589, -0.1871],
        [ 0.0915, -0.2216],
        [ 0.1006, -0.2590],
        [ 0.0796, -0.2114],
        [ 0.0555, -0.1635],
        [-0.0322, -0.0658],
        [ 0.0705, -0.2297],
        [-0.0124, -0.1116],
        [ 0.0646, -0.2398],
        [ 0.1270, -0.2171],
        [-0.0135, -0.0980],
        [ 0.1119, -0.2221],
        [ 0.1271, -0.2317],
        [ 0.0385, -0.1565],
        [ 0.1248, -0.2749],
        [-0.0051, -0.1190],
        [ 0.0298, -0

In [203]:
result_val = []
for batch_result in result:
    a = batch_result.tolist()
    for i in a:
        print(i)
        if i[0] > i[1]:
            result_val.append(0)
        else:
            result_val.append(1)

[0.08148691803216934, -0.2009236216545105]
[-0.04935155063867569, -0.12332257628440857]
[0.07847094535827637, -0.2384912073612213]
[-0.03926782310009003, -0.07406534254550934]
[0.025782085955142975, -0.20973576605319977]
[0.0043766312301158905, -0.1364857405424118]
[-0.0012408755719661713, -0.15018925070762634]
[0.09668417274951935, -0.21867690980434418]
[0.1088571771979332, -0.24166065454483032]
[0.12198606133460999, -0.22383081912994385]
[0.01319025456905365, -0.12043024599552155]
[0.08507494628429413, -0.2510247528553009]
[0.13122758269309998, -0.23996509611606598]
[-0.00011926144361495972, -0.14804567396640778]
[0.077763631939888, -0.21177998185157776]
[0.05985409393906593, -0.16607743501663208]
[0.07813044637441635, -0.18938079476356506]
[0.12915679812431335, -0.23374122381210327]
[0.10571527481079102, -0.22612042725086212]
[0.04455983266234398, -0.16021372377872467]
[0.03738655894994736, -0.14720644056797028]
[0.01860792189836502, -0.14676858484745026]
[0.020427117124199867, -0.1

[0.0026461277157068253, -0.1816181093454361]
[0.04647276923060417, -0.1601385474205017]
[0.07112562656402588, -0.2570401430130005]
[0.10404114425182343, -0.29136553406715393]
[0.09269849210977554, -0.21370667219161987]
[0.14677533507347107, -0.2408505380153656]
[0.11487741023302078, -0.2638745903968811]
[-0.010940492153167725, -0.09657277166843414]
[0.09622427821159363, -0.20031674206256866]
[0.10978434234857559, -0.22823509573936462]
[0.1214456632733345, -0.2380927950143814]
[0.09347977489233017, -0.22293055057525635]
[0.059009019285440445, -0.2443283498287201]
[0.08119232207536697, -0.196904718875885]
[0.10867146402597427, -0.22352807223796844]
[0.06688733398914337, -0.21710684895515442]
[0.1246819943189621, -0.23758400976657867]
[0.021748241037130356, -0.15290586650371552]
[0.07472780346870422, -0.1649017035961151]
[0.05061574652791023, -0.20534153282642365]
[-0.020173758268356323, -0.13881734013557434]
[0.15080441534519196, -0.25130099058151245]
[0.019256241619586945, -0.1555632054

[-0.03388863429427147, -0.09328457713127136]
[0.13060978055000305, -0.25680607557296753]
[0.1243862509727478, -0.25131359696388245]
[0.07530620694160461, -0.23155102133750916]
[0.12793171405792236, -0.22356699407100677]
[-0.04016992449760437, -0.13239213824272156]
[0.021981023252010345, -0.17944040894508362]
[0.10981354862451553, -0.23631471395492554]
[0.041592787951231, -0.17663723230361938]
[0.12334349006414413, -0.25918880105018616]
[-0.06078450754284859, -0.06169106811285019]
[0.10132691264152527, -0.23781755566596985]
[0.05135355889797211, -0.15586857497692108]
[0.03867293894290924, -0.17960074543952942]
[0.06616193801164627, -0.2372085303068161]
[0.1011003628373146, -0.20840679109096527]
[0.07957999408245087, -0.18988680839538574]
[0.06808814406394958, -0.19877779483795166]
[0.07000593841075897, -0.24755986034870148]
[0.12182745337486267, -0.2321009486913681]
[-0.009596854448318481, -0.17737635970115662]
[0.12665066123008728, -0.2254796028137207]
[0.07058264315128326, -0.17788513

[-0.028697146102786064, -0.15341588854789734]
[0.012725137174129486, -0.19681893289089203]
[-0.00079304538667202, -0.16064327955245972]
[0.11159224063158035, -0.220978245139122]
[-0.040604185312986374, -0.1296066790819168]
[0.12366774678230286, -0.2315087914466858]
[-0.04121585190296173, -0.1762448102235794]
[0.10741978883743286, -0.2812610864639282]
[0.10147122293710709, -0.24903222918510437]
[0.12343905121088028, -0.23178371787071228]
[0.07296494394540787, -0.2698037922382355]
[0.11032522469758987, -0.22594937682151794]
[0.0915011540055275, -0.20155496895313263]
[0.11811687797307968, -0.2588472366333008]
[0.07270624488592148, -0.2366989552974701]
[-0.001795932650566101, -0.16289596259593964]
[0.1254958063364029, -0.24811658263206482]
[0.09129858016967773, -0.18645891547203064]
[-0.025544892996549606, -0.13178196549415588]
[-0.016952404752373695, -0.1876838207244873]
[0.030514411628246307, -0.24488280713558197]
[0.06853468716144562, -0.16873079538345337]
[0.07516704499721527, -0.17611

[0.016256164759397507, -0.12740038335323334]
[0.10478077083826065, -0.1871664673089981]
[0.08237270265817642, -0.2240820825099945]
[0.00015833228826522827, -0.13275599479675293]
[0.11410659551620483, -0.20314040780067444]
[0.10482810437679291, -0.2343229502439499]
[-0.0019427761435508728, -0.1182054728269577]
[0.07659599930047989, -0.24775347113609314]
[0.020710542798042297, -0.21706511080265045]
[0.12175876647233963, -0.21653497219085693]
[-0.03367258608341217, -0.1302804946899414]
[0.1429048478603363, -0.23384693264961243]
[0.1245676577091217, -0.27467915415763855]
[0.025405384600162506, -0.1635097712278366]
[0.041463255882263184, -0.2488766312599182]
[0.12748979032039642, -0.2710556983947754]
[0.13523012399673462, -0.2357337921857834]
[0.0943339541554451, -0.22115997970104218]
[0.06346730887889862, -0.1968427151441574]
[0.1190485805273056, -0.24813511967658997]
[0.08762411773204803, -0.24026142060756683]
[0.07927146553993225, -0.20881132781505585]
[0.056343384087085724, -0.224669694

[0.11775291711091995, -0.2315416932106018]
[0.01021786779165268, -0.14360906183719635]
[0.08050835132598877, -0.22939814627170563]
[0.09945410490036011, -0.2586943209171295]
[0.09916704148054123, -0.24787752330303192]
[0.052239228039979935, -0.22730891406536102]
[0.12262419611215591, -0.23081916570663452]
[0.06978468596935272, -0.1974765509366989]
[-0.012164058163762093, -0.13848166167736053]
[0.017627619206905365, -0.20056931674480438]
[0.07804165780544281, -0.191632941365242]
[0.03959920257329941, -0.16242162883281708]
[0.1215958371758461, -0.25362229347229004]
[0.12042399495840073, -0.21697793900966644]
[0.014320813119411469, -0.145636647939682]
[-0.002764136530458927, -0.14338847994804382]
[0.01967903971672058, -0.14846815168857574]
[0.11698359251022339, -0.25578272342681885]
[-0.0072082579135894775, -0.18205422163009644]
[0.11420433223247528, -0.2666935920715332]
[0.07956552505493164, -0.24231654405593872]
[0.11512633413076401, -0.24229948222637177]
[0.03967971354722977, -0.218079

[0.13581444323062897, -0.23429054021835327]
[0.10150708258152008, -0.23142072558403015]
[0.03583816438913345, -0.16611617803573608]
[0.09489069879055023, -0.2276725172996521]
[0.1025751382112503, -0.24770128726959229]
[-0.083767369389534, -0.14348861575126648]
[0.09372515976428986, -0.25606635212898254]
[0.060447923839092255, -0.24831663072109222]
[0.06455857306718826, -0.2215314507484436]
[0.09493401646614075, -0.23744316399097443]
[0.02439330331981182, -0.21307887136936188]
[0.08946395665407181, -0.18833278119564056]
[-0.022325480356812477, -0.18821240961551666]
[0.09225127846002579, -0.25909024477005005]
[0.029825540259480476, -0.17504838109016418]
[0.11061412841081619, -0.20298248529434204]
[-0.012251762673258781, -0.11621508747339249]
[0.11377871036529541, -0.24077533185482025]
[0.0023070769384503365, -0.19416126608848572]
[0.023693392053246498, -0.13800185918807983]
[0.0016627795994281769, -0.11081486940383911]
[0.07042699307203293, -0.18984940648078918]
[0.033794280141592026, -0

[0.07812834531068802, -0.2619503438472748]
[-0.034267526119947433, -0.06568868458271027]
[0.10285686701536179, -0.23296386003494263]
[0.11353851109743118, -0.2420850396156311]
[-0.021577831357717514, -0.18660655617713928]
[0.015796352177858353, -0.13150757551193237]
[0.006571488454937935, -0.2133980393409729]
[0.015042588114738464, -0.2069929540157318]
[0.011175274848937988, -0.16982217133045197]
[0.10878397524356842, -0.2333734631538391]
[0.14458873867988586, -0.23311209678649902]
[0.002967621199786663, -0.2069033682346344]
[0.0941888615489006, -0.23111747205257416]
[0.09478812664747238, -0.22613480687141418]
[0.09665098786354065, -0.21074116230010986]
[-0.03138299286365509, -0.1542171835899353]
[0.10852960497140884, -0.2315659373998642]
[0.14625585079193115, -0.2440563589334488]
[0.0506618469953537, -0.19107499718666077]
[0.10242407768964767, -0.20681102573871613]
[0.03571175038814545, -0.1865302473306656]
[-0.02528535947203636, -0.15162412822246552]
[0.12548215687274933, -0.23234181

[0.12565933167934418, -0.24191373586654663]
[0.12182355672121048, -0.23064649105072021]
[0.14582008123397827, -0.24379760026931763]
[-0.05225115269422531, -0.13991282880306244]
[0.12140972912311554, -0.2702837586402893]
[0.010919880121946335, -0.16283473372459412]
[0.03245086967945099, -0.14405544102191925]
[0.13127733767032623, -0.22558483481407166]
[0.13426746428012848, -0.2425985485315323]
[-0.0807933434844017, -0.11319790780544281]
[0.13597707450389862, -0.2594720721244812]
[0.1050695925951004, -0.2497827112674713]
[0.11056005209684372, -0.2439468502998352]
[0.014131840318441391, -0.14272788166999817]
[0.08092524856328964, -0.19620878994464874]
[0.119764544069767, -0.23277242481708527]
[0.005860453471541405, -0.20591866970062256]
[0.11640363186597824, -0.21650348603725433]
[0.026074565947055817, -0.15589749813079834]
[0.12516199052333832, -0.2226201444864273]
[0.03707435727119446, -0.14944376051425934]
[0.055223409086465836, -0.24800139665603638]
[0.1300380527973175, -0.23786170780

[0.12248428910970688, -0.2373010367155075]
[0.1268431544303894, -0.20265798270702362]
[0.13043370842933655, -0.2317572832107544]
[-0.06338739395141602, -0.2091543972492218]
[0.04311450570821762, -0.19157908856868744]
[0.02046293020248413, -0.14088524878025055]
[0.09679365158081055, -0.23058122396469116]
[0.03788413107395172, -0.16629649698734283]
[0.020921476185321808, -0.23549240827560425]
[0.10184744000434875, -0.25254490971565247]
[-0.007386980578303337, -0.14578048884868622]
[0.060305994004011154, -0.198196142911911]
[0.012277995236217976, -0.25248512625694275]
[0.095791295170784, -0.24694721400737762]
[0.10924391448497772, -0.2464752346277237]
[0.10176383703947067, -0.2558426558971405]
[0.1348358541727066, -0.22589069604873657]
[0.0034409761428833008, -0.1610361933708191]
[0.06879059225320816, -0.2216356247663498]
[0.028825335204601288, -0.20803989470005035]
[0.13618159294128418, -0.24540631473064423]
[-0.02138938568532467, -0.08797310292720795]
[-0.0042043449357151985, -0.1707399

In [205]:
len(result_val)

11187

In [206]:
import csv

with open('laast.csv', 'w') as f:
    wr = csv.writer(f)
    wr.writerow(['Id', 'Predicted'])
    for i in range(len(result_val)):
        wr.writerow([i, result_val[i]])